# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AQ2WkxiDkd5f5es1aOrPujqcpGdMG_Po
"""

import pandas as pd
import numpy as np
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt

# 1. Dataset Load Karo
# (Dhyan rakho: Agar file ka naam alag hai toh yahan badal dena)
try:
    df = pd.read_csv('/content/data.csv', encoding='ISO-8859-1')
except FileNotFoundError:
    print("Error: 'data.csv' file nahi mili. Please file upload karein.")

# NO2 column ko clean karna (Null values hatana)
# Kaggle dataset mein column name 'no2' hota hai
x = df['no2'].dropna().values

# --- TUMHARA ROLL NUMBER ---
r = 102303183
# ---------------------------

# Step 1: Transformation Constants Calculate Karna
ar = 0.05 * (r % 7)
br = 0.3 * (r % 5 + 1)
print(f"Calculated ar: {ar}, br: {br}")

# Transform x into z
z = x + ar * np.sin(br * x)

# Step 2: PDF Prediction Function (Eq. 2)
def target_pdf(z, c, lambd, mu):
    return c * np.exp(-lambd * (z - mu)**2)

# Fitting ke liye data prepare karna
# Histogram se probability density nikalna
counts, bin_edges = np.histogram(z, bins=100, density=True)
bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2

# Initial Guess (mu = mean of z, lambda = small value, c = peak height)
initial_guess = [np.max(counts), 0.001, np.mean(z)]

# Curve Fitting (Parameters Lambda, Mu, C estimate karna)
try:
    params, _ = curve_fit(target_pdf, bin_centers, counts, p0=initial_guess)
    c_val, lambd_val, mu_val = params

    print("\n--- FINAL PARAMETERS ---")
    print(f"Lambda (λ): {lambd_val}")
    print(f"Mu (μ): {mu_val}")
    print(f"C: {c_val}")
    print("------------------------")

    # Visualization (Optional: Result check karne ke liye)
    plt.hist(z, bins=100, density=True, alpha=0.6, color='g', label='Transformed Data (z)')
    plt.plot(bin_centers, target_pdf(bin_centers, *params), 'r-', lw=2, label='Fitted PDF')
    plt.legend()
    plt.title(f"PDF Fitting for Roll No: {r}")
    plt.show()

except Exception as e:
    print(f"Fitting mein error aaya: {e}")